#ifndef TREESTREAM_H
#define TREESTREAM_H
//----------------------------------------------------------------------------
// File: treestream.h
//
// Description: The classes itreestream and otreestream provide a convenient 
//              interface to the kind of Root trees typically used in HEP
//              analyses. Our (default) assumption is that there is one tree 
//              per Root file and the objects stored are simple types. The
//              treestream classes hide the boilerplate code for getting at 
//              the tree, its branches and leaves.
//
//              The design is based on the observation that, ultimately, data
//              reduce to a set of name/value pairs in which the value 
//              can be regarded as a homogeneous sequence of doubles, floats 
//              longs, or ints. Moreover, an arbitrarily complex graph of the 
//              name/value pairs is readily achieved with, well, name/value 
//              pairs! Name/value pair is just another name for variable.
// 
//              Thinking in terms of objects, in the context of high energy 
//              physics analysis, has yielded undue complexity. On the other 
//              hand, thinking in terms of name/value pairs reduces the 
//              complexity considerably. The irreducible complexity, which 
//              surely exists, properly resides in the graph generated by 
//              the set of name/value pairs, that is, variables.
//
//              Of course, it is often convenient to package name/value pairs 
//              into objects to avail oneself of their useful behaviour. This 
//              may be useful, for example, to model a particularly 
//              complicated sub-graph of name/value pairs. Or it may be that
//              one wishes to take advantage of an object that defines
//              useful functions on the name/value pairs. A  nice example of 
//              packaging name/value pairs for this reason is the packaging 
//              of the name/value pairs, Px, Py, Pz and E into 
//              TLorentzVector objects to take advantage of the host of 
//              useful mathematical operations these objects define on them.
//
// Created: 19-Feb-2005 Harrison B. Prosper, based on 12-Mar-2001 version of
//                      the same.
//          14-Jul-2005 Allow for arrays
//          13-Aug-2005 Tidy up
//          11-Aug-2007 Add ls() method as a proxy for print
//          06-Jun-2010 Add store and save (commt = store + save)
//          23-Sep-2010 Move from PhysicsTools/LiteAnalysis to 
//                                PhysicsTools/TheNtupleMaker
//          22-Nov-2010 Allow reading of multiple trees using friend
//                      mechanism
//          22-Nov-2011 Handle storing of strings
//          01-Mar-2018 Fix chain/friend interactions (at 35,000 feet!)
//          23-Sep-2018 split into itreestream.h and otreestream.h
//----------------------------------------------------------------------------
#include <vector>
#include <string>
#include <list>
#include <map>
#include <sstream>
#include <iostream>
#include <typeinfo>
#include <cctype>

#include "TFile.h"
#include "TTree.h"
#include "TLeaf.h"
#include "TBranch.h"
#include "TChain.h"

#include "itreestream.h"
#include "otreestream.h"

#endif
